# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638b9f38a181024123983f32cc2e3b4fe44908945850e5bfdae5393cd752ce601b48fa8f359b6fc10ccf5b8e0f3e7875f5dd621e106b8de219ce4a265593910f

test:
  secret_key_base: 758b16dab049edf1f6a484c776a7e15f1251c7e050a8b18af2716a7dc94d02d24bcec31ad99b48027ef95679c9cdf788f46e28335c7a77056389bfcb88bd003f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
